### ISSUE TITLE
Could there be an external way to associate a Schema file?

### ISSUE THREAD

**Issue by philschatz** [aerhard/linter-autocomplete-jing#26]
Thanks for the great plugin! 🎉 

At https://openstax.org we edit XML files that match a RNG schema but unfortunately we do not provide a schema URL in those files. Instead, we rely on a file extension (`*.cnxml`).

Could there be a setting that allows the plugin to resolve a default schema if none is provided in the file? Maybe a setting that allows a text field like `*.cnxml|rng|/path/to/file.rng *.foo.xml|rng|/path/to/another.rng`?

I started looking around the code and it seems that `getSchemaProps.js` could parse that setting and append it to `schemaProps` if `textEditor.getFileName()` matches one of the glob patterns.

Something like that would really help us out; do you think it would be a useful feature to add?

**Comment by aerhard** [comment]
Hi Phil -- Thank you! I absolutely agree, it would be great to have that feature -- I think that should be the next thing to implement. There's already a partial implementation at https://github.com/aerhard/linter-autocomplete-jing/pull/25 which evaluates 'rules' allowing you to associate schemata or catalogs with documents based on the file path or the namespace / localname / attributes of the root element. The branch is not ready for use yet because the part which reads these rules from the user still needs to get added. There are a couple of options how users could provide them, like 1) putting them into the package config, 2) read the rules from other 'schema provider' packages (which would include the matching rules as well as the schemata themselves) or 3) evaluate project-specific config files like '.eslintrc.json'. Option 1 would be the most straightforward one to implement but it's also limited: Users would't be able to change the config data with Atom's settings view UI since the rule data is too deeply nested; and there's no way to automatically provide the actual schemata with this approach. So I tend to prefer options 2 or 3. What's your thoughts?

**Comment by reedstrm** [comment]
I'm a colleague of Phil's, thought I'd chime in here. I was wondering this could leverage the file-types mechanism, since it would replace mucking with the customFileTypes config to associate `.cnxml` with `text.xml`. Instead, we'd define/associate it with a custom type `text.xml.cnxml`, and provide a hash somewhere that provides the schema to go with the custom type. I realize the 'provide a hash somewhere' is pretty much the same missing UI you mention above ... (don't mind me if this is all obvious/off-point, I'm the python/XML/DB guy, not the JS guy :-) )  Hmm, @philschatz  in the context of the CPT, I think we could actually get away with adding the processing instruction at checkout, with the custom tool.

**Comment by aerhard** [comment]
If we implement 'option 2' you could create a package which both defines the `text.xml.cnxml` grammar as an extension of `text.xml` (associating that grammar with your custom file extension) and contains rules for the linter-autocomplete-jing package which associates the `text.xml.cnxml` grammar with the schema you'd like to use for validation/autocomplete. You could then distribute that package via APM or share it privately (and `apm link` that package on each computer). I'd like to do something similar with commonly used schemata like the ones used for XSD, RNG etc files. Would something like that be helpful for you? Maybe it would still make sense to support providing all that information if Atom's `config.cson`. I've experimented with that yesterday. In addition to changing `customFileTypes` in `config.cson` you could add something like this:

```
"linter-autocomplete-jing":
  rules: [
    {
      priority: 1
      test:
        pathRegex: ".rng$"
      outcome:
        schemaProps: [
          {
            lang: "rng"
            path: "/path/to/relaxng.rng"
          }
        ]
    }
    {
      priority: 1
      test:
        rootNs: "urn:oasis:names:tc:entity:xmlns:xml:catalog"
      outcome:
        schemaProps: [
          {
            lang: "rnc"
            path: "/path/to/catalog.rnc"
          }
        ]
    }
  ]
```

'Option 2' is probably more convenient for end users who just want to edit files without setting up a lot of things

**Comment by reedstrm** [comment]
That sounds useful. If I understand correctly, we'd need to implement support in linter-autocomplete-jing for finding and using these rules. By looking for them in more than one place, we could play with it via editing the config, then eventually wrap up our own package to distribute along side our docs, so other atom users can install it via the typical package process? I think I just voted in favor of "all of them, and a pony", but yeah. :-)

**Comment by philschatz** [comment]
Thanks for helping out with our probably niche use case!

It seems like the option outlined in your most-recent comment would be the easiest to get implemented and address the problem we currently have ("only the file extension or namespace in the file defines which schema to use"). It's much nicer than the hack I initially suggested.

I was curious, what does the `priority:` field provide that could not be inferred from the order of items in `rules:`? I was thinking of submitting a PR adding the feature you described (at least the `rootNs` version)

**Comment by aerhard** [comment]
that would be fantastic! We don't need the priority field when all information is in a single array, but I'd also like to gather rules from different packages in a way a package author can 'override' an existing rule. An example would be the official TEI schema which some editorial projects use as a basis for a customized schema.

**Comment by aerhard** [comment]
I've created a new PR as a supplement to rules support in `config.cson` -- it adds support for rules (and custom grammars / file extensions) provided in a separate package. With this approach you would only need to make one package available and users wouldn't have to make any changes in `config.cson`. Here's a demo package https://github.com/aerhard/xml-demo-package which could theoretically be published on the Atom Package Repository. For testing, you can check out the linter-autocomplete branch at https://github.com/aerhard/linter-autocomplete-jing/pull/29, clone the demo package from https://github.com/aerhard/xml-demo-package and then apm link it (possibly restart Atom). When you open the file `test/test.demoxyext`, Atom should recognize the file extension and provide syntax  highlighting and linter / autocomplete should take the schema file in `schemata/demoxy.rng` into account. We could combine this addition with rules support in `config.cson` (which still makes sense).
