### ISSUE TITLE
error on xinclude that doesn't appear in Oxygen xml editor

### ISSUE THREAD

**Issue by jeffreycwitt** [aerhard/linter-autocomplete-jing#44]
This is not a bug, but a confusion. I'm getting different behaviors dealing with xinclude when validating the same xml file with the same schema in Oxygen and in Atom.

Might you try this file on your own system?

https://bitbucket.org/jeffreycwitt/ppr-lectio17/raw/996460a757cdaf88dabef234af5247ebc6bacb1a/pal_ppr-lectio17.xml

In Oxygen there is no error. 

But in Atom I get this error: 

RNG element "xi:include" not allowed here; expected the element end-tag or element "ab", "addSpan", "alt", "altGrp", "anchor", "app", "argument", "bibl", "biblFull", "biblStruct", "byline", "cb", "cit", "damageSpan", "dateline", "delSpan", "desc", "div", "divGen", "docAuthor", "docDate", "epigraph", "floatingText", "fw", "gap", "gb", "head", "index", "interp", "interpGrp", "join", "joinGrp", "l", "label", "lb", "lg", "link", "linkGrp", "list", "listApp", "listBibl", "listEvent", "listNym", "listOrg", "listPerson", "listPlace", "listTranspose", "listWit", "meeting", "metamark", "milestone", "msDesc", "note", "opener", "p", "pb", "q", "quote", "said", "salute", "signed", "sp", "space", "span", "spanGrp", "stage", "substJoin", "timeline" or "witDetail"

Remove the schema declaration and the error goes away.

However, again, in Oxygen the document validates with the schema declaration and xinclude present? Any ideas what's going on?

BTW, It's a fantastic plug-in. And if I can fix this error, I plan to use it heavily! Where's your "donate" button?

**Comment by aerhard** [comment]
Hi, thanks a lot! If I remember it right, oXygen's got a config option to turn on xinclude-aware validation which checks validity of the 'composed' document (with all xincludes resolved) instead of the raw document you see in the editor. The schema at https://raw.githubusercontent.com/lombardpress/lombardpress-schema/master/src/out/diplomatic.rng doesn't allow xinclude elements. You could modify it (or rather, the ODD) so it won't complain about the xinclude elements but the ideal solution would be to add support for xinclude-aware validation in the Atom plug-in (there's support for xincludes in Java's SAXParser)

**Comment by aerhard** [comment]
This should be fixed now -- please re-open the ticket if there are further issues
