### ISSUE TITLE
Catalogs do not work as expected

### ISSUE THREAD

**Issue by stefan-jung** [aerhard/linter-autocomplete-jing#53]
I cannot get the catalog processing working. The following file ([carMaintenance.dita](https://github.com/oxygenxml/dita-relaxng-defaults/blob/master/samples/tasks/carMaintenance.dita)) throws a `Could not process schema or catalog` error. The DITA grammars can be found [here](https://github.com/oasis-tcs/dita/tree/master/doctypes) for testing.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="urn:oasis:names:tc:dita:rng:task.rng" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="urn:oasis:names:tc:dita:rng:task.rng" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<task id="carMaintenance">
    <title>Car Maintenance</title>
    <shortdesc>Avoid costly repairs by constantly performing simple maintenance tasks.</shortdesc>
    <taskbody/>
</task>
```

This is my **config.cson**:

```
"*":
  core:
    telemetryConsent: "limited"
  "exception-reporting":
    userId: "3701b290-4444-420b-9784-a1192315e69b"
  "linter-autocomplete-jing":
    displaySchemaWarnings: true
    rules: [
      {
        priority: 1
        test:
          rootNs: "urn:oasis:names:tc:dita:rng:task.rng"
        outcome:
          xmlCatalog: "/home/stefan/workspace/DITA/dita-ot/plugins/org.oasis-open.dita.v1_3/rng/technicalContent/catalog.xml"
      }
    ]
  "linter-ui-default": {}
```

**Comment by aerhard** [comment]
I'm sorry for the late reply -- must have overlooked the notification. In case it's still relevant: The test in `config.cson` doesn't match the document above since

```
rootNs: "urn:oasis:names:tc:dita:rng:task.rng"
```

would require `xmlns="urn:oasis:names:tc:dita:rng:task.rng"` on the root element. You could instead use `rootLocalName: "task"` or, if that's not specific enough, a path regex (see https://github.com/aerhard/linter-autocomplete-jing/blob/master/README.md).
